#pragma once

/* ICDC internal register access control register(RGADW) */
#define ICDC_RGADW_RGWR			BIT(16)

#define ICDC_RGADW_RGADDR_OFFSET	8
#define	ICDC_RGADW_RGADDR_MASK		GENMASK(14, ICDC_RGADW_RGADDR_OFFSET)

#define ICDC_RGADW_RGDIN_OFFSET		0
#define	ICDC_RGADW_RGDIN_MASK		GENMASK(7, ICDC_RGADW_RGDIN_OFFSET)

/* ICDC internal register data output register (RGDATA)*/
#define ICDC_RGDATA_IRQ			BIT(8)

#define ICDC_RGDATA_RGDOUT_OFFSET	0
#define ICDC_RGDATA_RGDOUT_MASK		GENMASK(7, ICDC_RGDATA_RGDOUT_OFFSET)

/* Internal register space, accessed through regmap */
enum {
	SCODA_REG_SR = 0x0,
	SCODA_REG_SR2,
	SCODA_REG_SIGR,
	SCODA_REG_SIGR2,
	SCODA_REG_SIGR3,
	SCODA_REG_SIGR5,
	SCODA_REG_SIGR7,
	SCODA_REG_MR,
	SCODA_REG_AICR_DAC = 0x08,
	SCODA_REG_AICR_ADC,
	SCODA_REG_CR_DMIC,
	SCODA_REG_CR_MIC1,
	SCODA_REG_CR_MIC2,
	SCODA_REG_CR_DAC = 0x0d,
	SCODA_REG_CR_DAC2,
	SCODA_REG_CR_ADC,
	SCODA_REG_CR_MIX = 0x10,
	SCODA_REG_DR_MIX,
	SCODA_REG_CR_VIC,
	SCODA_REG_CR_CK,
	SCODA_REG_FCR_DAC = 0x14,
	SCODA_REG_SFCCR_DAC,
	SCODA_REG_SFFCR_DAC,
	SCODA_REG_FCR_ADC,
	SCODA_REG_CR_TIMER_MSB,
	SCODA_REG_CR_TIMER_LSB,
	SCODA_REG_ICR,
	SCODA_REG_IMR,
	SCODA_REG_IFR,
	SCODA_REG_IMR2,
	SCODA_REG_IFR2,
	SCODA_REG_GCR_DACL,
	SCODA_REG_GCR_DACR,
	SCODA_REG_GCR_DACL2,
	SCODA_REG_GCR_DACR2,
	SCODA_REG_GCR_MIC1,
	SCODA_REG_GCR_MIC2,
	SCODA_REG_GCR_ADCL,
	SCODA_REG_GCR_ADCR,
	SCODA_REG_GCR_MIXDACL,
	SCODA_REG_GCR_MIXDACR,
	SCODA_REG_GCR_MIXADCL,
	SCODA_REG_GCR_MIXADCR,
	SCODA_REG_CR_DAC_AGC,
	SCODA_REG_DR_DAC_AGC,
	SCODA_REG_CR_DAC2_AGC,
	SCODA_REG_DR_DAC2_AGC,
	SCODA_REG_CR_ADC_AGC,
	SCODA_REG_DR_ADC_AGC,
	SCODA_REG_SR_ADC_AGCDGL,
	SCODA_REG_SR_ADC_AGCDGR,
	SCODA_REG_SR_ADC_AGCAGL,
	SCODA_REG_SR_ADC_AGCAGR,
	SCODA_REG_CR_TR,
	SCODA_REG_DR_TR,
	SCODA_REG_SR_TR1,
	SCODA_REG_SR_TR2,
	SCODA_REG_SR_TR_SRCDAC,

/*  icdc_d3 internal register extend space */
	SCODA_MIX_0,
	SCODA_MIX_1,
	SCODA_MIX_2,
	SCODA_MIX_3,
	SCODA_MIX_4,

	SCODA_DAC_AGC0,
	SCODA_DAC_AGC1,
	SCODA_DAC_AGC2,
	SCODA_DAC_AGC3,

	SCODA_DAC2_AGC0,
	SCODA_DAC2_AGC1,
	SCODA_DAC2_AGC2,
	SCODA_DAC2_AGC3,

	SCODA_ADC_AGC0,
	SCODA_ADC_AGC1,
	SCODA_ADC_AGC2,
	SCODA_ADC_AGC3,
	SCODA_ADC_AGC4,
	SCODA_MAX_REG_NUM,
};

/*aicr dac*/
#define SCODA_AICR_DAC_ADWL_SHIFT (6)
#define SCODA_AICR_DAC_ADWL_MASK (0x3 << SCODA_AICR_DAC_ADWL_SHIFT)
#define SCODA_AICR_DAC_SLAVE_SHIFT (5)
#define SCODA_AICR_DAC_SLAVE_MASK (0x1 << SCODA_AICR_DAC_SLAVE_SHIFT)
#define SCODA_AICR_DAC_SLAVE (1 << 5)
#define SCODA_AICR_DAC_SB_SHIFT (4)
#define SCODA_AICR_DAC_SB_MASK (0x1 << SCODA_AICR_DAC_SB_SHIFT)
#define SCODA_AICR_DAC_AUDIOIF_SHIFT (0)
#define SCODA_AICR_DAC_AUDIO_MASK (0x3 << SCODA_AICR_DAC_AUDIOIF_SHIFT)
#define SCODA_AICR_DAC_AUDIOIF_I2S (0x3)

/* aicr adc */
#define SCODA_AICR_ADC_ADWL_SHIFT (6)
#define SCODA_AICR_ADC_ADWL_MASK (0x3 << SCODA_AICR_ADC_ADWL_SHIFT)
#define SCODA_AICR_ADC_SB_SHIFT (4)
#define SCODA_AICR_ADC_SB_MASK (0x1 << SCODA_AICR_ADC_SB_SHIFT)
#define SCODA_AICR_ADC_AUDIOIF_SHIFT (0)
#define SCODA_AICR_ADC_AUDIO_MASK (0x3 << SCODA_AICR_ADC_AUDIOIF_SHIFT)
#define SCODA_AICR_ADC_AUDIOIF_I2S (0x3)

/* cr vic */
#define SCODA_CR_VIC_SB_SHIFT (0)
#define SCODA_CR_VIC_SB_MASK (1 << SCODA_CR_VIC_SB_SHIFT)
#define SCODA_CR_VIC_SB_SLEEP_SHIFT (1)
#define SCODA_CR_VIC_SB_SLEEP_MASK (1 << SCODA_CR_VIC_SB_SLEEP_SHIFT)

/* fcr adc/dac */
#define SCODA_FCR_FREQ_SHIFT (0)
#define SCODA_FCR_FREQ_MASK (0xf << SCODA_FCR_FREQ_SHIFT)

/* cr dac */
#define SCODA_CR_DAC_SMUTE_SHIFT (7)
#define SCODA_CR_DAC_SMUTE_MASK (0x1 << SCODA_CR_DAC_SMUTE_SHIFT)
#define SCODA_CR_DAC_SB_SHIFT (4)
#define SCODA_CR_DAC_SB_MASK (0x1 << SCODA_CR_DAC_SB_SHIFT)
#define SCODA_CR_DAC_ZERO_SHIFT (0)
#define SCODA_CR_DAC_ZERO_MASK (0x1 << SCODA_CR_DAC_ZERO_SHIFT)

/* cr dac */
#define SCODA_CR_ADC_SMUTE_SHIFT (7)
#define SCODA_CR_ADC_SMUTE_MASK (0x1 << SCODA_CR_ADC_SMUTE_SHIFT)
#define SCODA_CR_ADC_MIC_SEL_SHIFT (6)
#define SCODA_CR_ADC_MIC_SEL_MASK (0x1 << SCODA_CR_ADC_MIC_SEL_SHIFT)
#define SCODA_CR_ADC_SB_SHIFT (4)
#define SCODA_CR_ADC_SB_MASK (0x1 << SCODA_CR_ADC_SB_SHIFT)
#define SCODA_CR_ADC_ZERO_SHIFT (0)
#define SCODA_CR_ADC_ZERO_MASK (0x1 << SCODA_CR_ADC_ZERO_SHIFT)

/* ifr */
#define SCODA_IFR_DAC_MUTE_SHIFT (0)
#define SCODA_IFR_DAC_MUTE_MASK (0x1 << SCODA_IFR_DAC_MUTE_SHIFT)
#define SCODA_IFR_ADC_MUTE_SHIFT (2)
#define SCODA_IFR_ADC_MUTE_MASK (0x1 << SCODA_IFR_ADC_MUTE_SHIFT)
#define SCODA_IFR_ADAS_LOCK_SHIFT (7)
#define SCODA_IFR_ADAS_LOCK_MASK (0x1 << SCODA_IFR_ADAS_LOCK_SHIFT)

/* cr ck */
#define SCODA_CR_CK_MCLK_DIV_SHIFT (6)
#define SCODA_CR_CK_MCLK_DIV_MASK (0x1 << SCODA_CR_CK_MCLK_DIV_SHIFT)
#define SCODA_CR_CK_SDCLK_SHIFT (4)
#define SCODA_CR_CK_SDCLK_MASK (0x1 << SCODA_CR_CK_SDCLK_SHIFT)
#define SCODA_CR_CRYSTAL_SHIFT (0)
#define SCODA_CR_CRYSTAL_MASK (0xf << SCODA_CR_CRYSTAL_SHIFT)

/* icr */
#define SCODA_ICR_INT_FORM_SHIFT (6)
#define SCODA_ICR_INT_FORM_MASK (0x3 << SCODA_ICR_INT_FORM_SHIFT)
#define SCODA_ICR_INT_FORM_HIGH (0)
#define SCODA_ICR_INT_FORM_LOW  (1)

/* imr */
#define SCODA_IMR_COMMON_MASK (0xff)
#define SCODA_IMR2_COMMON_MASK (0xff)