# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_JZ4740_QI_LB60)		+= qi_lb60.dtb
dtb-$(CONFIG_JZ4740_RS90)		+= rs90.dtb
dtb-$(CONFIG_JZ4770_GCW0)		+= gcw0.dtb
dtb-$(CONFIG_JZ4780_CI20)		+= ci20.dtb
dtb-$(CONFIG_X1000_CU1000_NEO)		+= cu1000-neo.dtb
dtb-$(CONFIG_X1830_CU1830_NEO)		+= cu1830-neo.dtb
dtb-$(CONFIG_X1000_NANO_EVB)		+= x1000-nano-evb.dtb
dtb-$(CONFIG_X1000_NANO_EVB_NAND)	+= x1000-nano-evb-nand.dtb
dtb-$(CONFIG_X1501_PICO_EVB)		+= x1501-pico-evb.dtb
dtb-$(CONFIG_X1000_NOTKIA_V2)		+= notkia-v2.dtb
dtb-$(CONFIG_X1501_LOSHARK_V2)		+= loshark-v2.dtb
dtb-$(CONFIG_X1000_INGENIC_JDI_V1)	+= jdi-v1.dtb
dtb-$(CONFIG_X1501_SUDOMAKER_CANBOX)	+= sudomaker-canbox.dtb
dtb-$(CONFIG_X1000_SUDOMAKER_CLE)	+= sudomaker-cle.dtb
dtb-$(CONFIG_X2000_CU2000_NEO)		+= cu2000-neo.dtb
dtb-$(CONFIG_X2000_HALLEY5)		+= halley5.dtb


obj-$(CONFIG_BUILTIN_DTB)		+= $(addsuffix .o, $(dtb-y))
